### ISSUE TITLE
Edit style for mobile friendly design

### ISSUE THREAD

**Issue by NetPenguins** [spotify/backstage-microsite#191]
This was discovered on iPhone X running version 13.5.1

### Possibly resize font or control text wrap so the overflow doesn't happen like below.
![IMG_4509 2](https://user-images.githubusercontent.com/20445056/86825206-17158800-c05d-11ea-9746-d23e23cd198d.PNG)

### Set the iframe element to fit the content block. On on mobile clicking will often present full screen anyways.

![image](https://user-images.githubusercontent.com/20445056/86824075-a5890a00-c05b-11ea-94b5-0c81e80fc218.png)

**Comment by NetPenguins** [comment]
## Proposed Solution:

For the Header Titles we could add the following into custom.css:

```css
@media only screen and (max-width: 400px) {
  .Block__Title{
    word-break: keep-all;
    font-size: 43px;
    line-height: 45px;
  }
}
```
This allows the font to fit the mobile screen more naturally. 

For the iframe styling I will propose a new component like:
```js
Block.MediaFrame
```

or we could extend the `Block.TextBlock` like this: 
```js
Block.TextBox = simpleComponent('div', 'Block__TextBox', ['wide', 'video'])
```
and style the `--video` element. 

I would argue in favor of the `Block.MediaFrame` approach as it makes it easier to maintain.
